# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d61fd66bbb680e4f569270ba313442492cd9c736a0f341123400ae4db11c6a6e03024b6f563d462b39e0277ccab2a40dd5992f57ad06579ec0966d8392bc0428

test:
  secret_key_base: 160c8fc7d781627bf7f39b830bbfc91b1681a8e2e84d656745035bbef77538dc830457a8ab34d4717b62e77cf01e9eeb743f91eb2e08fff7b4ef60d0d511fb0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
